---
title: "Assignment"
author: "Hanwen Miao"
date: today
format: html
params:
  season_no: 1
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(dplyr)
library(stringr)
```

```{r}
file_path <- paste0("C:/Users/lulut/Desktop/forked/Data/got/season_", params$season_no, ".RData")
load(file_path)
```

# Game of Thrones - Summary

### __(*Warning:* spoilers ahead)__
#web scraping-Season-1
### Overview 
```{r}
url <- paste0("https://en.wikipedia.org/wiki/Game_of_Thrones_(season_", params$season_no, ")")
webpage <- read_html(url)
intro_nodes <- webpage %>% html_nodes("p")
intro_text <- intro_nodes %>% html_text() %>% .[1:2] %>% str_c(collapse = "\n\n")
print(intro_text)
```
#### Audiences statistics
```{r}
season_no <- params$season_no
episodes_no <- nrow(season_data)
date_start <- season_data$premiere_date[1]
date_end <- season_data$premiere_date[episodes_no]
viewers <- mean(season_data$viewers)
viewers_start <- season_data$viewers[1]
viewers_end <- season_data$viewers[episodes_no]
max_viewers <- max(season_data$viewers)
top_episode_desc <- season_data$description[season_data$viewers == max_viewers]
most_watched <- season_data[season_data$viewers == max_viewers, ]

summary1 <- paste(
  "Season", season_no, "of Game of Thrones consisted of", episodes_no, "episodes that aired between", 
  date_start, "and", date_end, "on HBO.",
  "The show gathered an average of", viewers, "million first-day TV viewers in the US,",
  "with the number growing from", viewers_start, "million to", viewers_end, "million by the end of the season.",
  "The most popular episode of the season was", most_watched$title, ", in which:",
  top_episode_desc
)
print(summary1)
```
***

You can see how the viewership of the episodes changed in Figure 1.

```{r}
plot(season_data$viewers, type="l", col="red", lwd=2, 
     xlab = "Episode number", 
     ylab = "1st day TV viewers in the US (millions)",
     main = paste("Season", params$season_no, "Viewers"))
```
```


***

Finally, the episodes with the above-average viewership were:
```{r}
season_data[season_data$viewers > mean(season_data$viewers), c("no_season", "title", "directed_by")]
```

